[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Build tasks for SysCallMeMaybe"

[dependencies]
anyhow.workspace = true
clap.workspace = true
